export const Colors = {
  light: {
    primary: "#76CABB",
    blackText: "#000",
    greenText: "#76CABB",
    whiteText: "#FFF",
    redText: "#DB4437",
    background: "#FFF",
    icon: "#000",
    tabIconDefault: "#687076",
    button: "#76CABB",
    track: "#FFE9F1",
  },
  dark: {
    primary: "#76CABB",
    blackText: "#000",
    greenText: "#76CABB",
    whiteText: "#FFF",
    redText: "#DB4437",
    background: "#FFF",
    icon: "#000",
    tabIconDefault: "#687076",
    button: "#76CABB",
    track: "#FFE9F1",
  },
};
